# docker-compose.yml
version: "3.8"
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.routes
    container_name: dashboard_backend
    ports:
      - "8000:8000"
    env_file:
      - .env

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.app
    container_name: dashboard_frontend
    ports:
      - "8501:8501"
    env_file:
      - .env
    depends_on:
      - backend
